### ISSUE TITLE
Team3-Assessment-TravisCI-thoughts

### ISSUE THREAD

**Issue by Jordan-A** [Allegheny-Computer-Science-203-S2020/cs203-S2020-assessment#6] opened 2020-01-20 23:35 UTC
For the assessment key in assessment.md FILE it does not match up with the later assessment scales using the markdown template.  There is no team responsible for this section.  When we merge the technical leaders should choose our section and discard the master.

Could we copy the template into the top section of the assessment.md File?

The issue could be found at https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-assessment/commit/845d7d2f614c776be19620d7f870c7662dfb9265#diff-692c8e8921865a9687ae9a5c8a86f2ad

**Comment by reid7danny** [comment] 2020-01-20 23:46
I used the emojis as the template for the assessment guide. I don't know which one is right or wrong, but I just followed the markdown. Hopefully someone will clarify that up...

**Comment by lussierc** [comment] 2020-01-20 23:47
Good observation, @Jordan-A. I was wondering the same thing with regard to whether or not we should change the Template at the top of the document. As there is no team that is assigned to directly do this, I will make a commit to fix this issue and add the new scale. Then we will have the correct assessment scales regardless of whether or not someone else deals with it later on.

**Comment by lussierc** [comment] 2020-01-20 23:48
I am also going to add the emoji's as the template at the top of the guide @reid7danny. I believe we should be using the emoji's as they are apart of the newest template for this in the markdown repository.

**Comment by reid7danny** [comment] 2020-01-20 23:48
nice good call @lussierc

**Comment by Jordan-A** [comment] 2020-01-20 23:49
Great! I'm one of the point persons for the markdown team and I can verify that we should follow the markdown file.

**Comment by reid7danny** [comment] 2020-01-20 23:50
Cool. @Jordan-A It shouldn't matter too much which template we decide to use. It is an easy change to fix, as long as we all are on the same page.

**Comment by liux2** [comment] 2020-01-20 23:51
Ye, I think we should follow the markdown template. The issue is there is no team responsible for the assessment key section. When we merging team3 branch into master, the technical leaders can choose our section over the master section.

**Comment by lussierc** [comment] 2020-01-20 23:55
I have added the updated markdown template to the criteria section at the top of our `assessment.md` file. I have added all team members involved in the decision-making process as co-authors on the fixing commit, which can be found in the `team3-travisci-section` branch.

**Comment by liux2** [comment] 2020-01-20 23:58
Let's keep this issue open for other problems related to this branch. We can close it after we all contribute it. Marisol is in a meeting right now, she will be back soon. I will keep reading the section.

**Comment by liux2** [comment] 2020-01-21 00:08
I have a question for TravisCI, do we have to choose TravisCI over other build tools? If it is only the skills we should master, could it be:
1. `Does not know any type of setup or configuration of Travis CI` over `Does not perform any type of setup or configuration of Travis CI`
2. `Does not know how to use Travis CI to perform secure releases of project deliverables` over `Does not use Travis CI to perform secure releases of project deliverables`
3. `Does not know how to create third-party integrations with Travis CI` over `Does not create third-party integrations with Travis CI`

**Comment by lussierc** [comment] 2020-01-21 00:12
@liux2 I think TravisCI is the only Continuous Integration build tool we will be using in the class. I see your argument with this but I personally feel we should leave the writing as it is right now because "performing" one of these tasks implies that they must know how to do it, or else they would have been unable to perform the task.

**Comment by hodevin** [comment] 2020-01-21 00:13
@liux2  It shouldn't really make a difference. But if it makes it a skill we need to master since we are only using Travis CI as the main build tool, then we can change it to your suggestion.

**Comment by gkapfham** [comment] 2020-01-21 00:51
Hello @Jordan-A can you please add an icon or a photograph to your GitHub profile?

**Comment by gkapfham** [comment] 2020-01-21 00:52
Hi @liux2, your question is a really good one! I suggest that we focus on using Travis CI, although I agree that we could also consider using Circle CI, AppVeyor, GitHub Actions or many other CI systems. Unless someone else feels strongly about this issue, I suggest that we use Travis CI. What do others think?

**Comment by lussierc** [comment] 2020-01-21 01:27
> Hi @liux2, your question is a really good one! I suggest that we focus on using Travis CI, although I agree that we could also consider using Circle CI, AppVeyor, GitHub Actions or many other CI systems. Unless someone else feels strongly about this issue, I suggest that we use Travis CI. What do others think?

@gkapfham I would prefer to use Travis CI as most students in the class have already encountered the tool in their introductory Computer Science courses. That way most everyone already has a general understanding of how it works. I also have heard of Travis CI being used in industry which would be helpful for students even after the course is finished.

**Comment by lussierc** [comment] 2020-01-21 18:49
As a pull request (PR #7) has now been made for the work discussed in this Issue, I am closing the Issue.

Any further discussion about this section should continue in the aforementioned PR.

**Closed as completed by lussierc** 2020-01-21 18:49 UTC
Labels: enhancement, question
